### ISSUE TITLE
Release on pypi?

### ISSUE THREAD

**Issue by Martronic-SA** [collective/collective.relationfieldwidget#1]
I've just installed the product and it seems to do the job!
Should it be released on Pypi so people ca install it easily?

**Comment by mauritsvanrees** [comment]
@dpopsmg Since you are the only contributor on this package, it would be great if you could make a release on https://pypi.python.org

**Comment by jensens** [comment]
@Martronic-SA you can do releases on your own. If you need guidance please ask here or over at community.plone.org. 
Hint: README.rst needs some love.

**Comment by Martronic-SA** [comment]
Release has been done:
https://pypi.python.org/pypi/collective.relationfieldwidget/1.0a1

**Comment by mauritsvanrees** [comment]
@Martronic-SA Could you add 'collective' as owner of the package on PyPI? I don't know who has access to the collective account, but then at least some other people can do releases too if needed.
Just a suggestion.

**Comment by Martronic-SA** [comment]
It's done!
Thank you!
